---
:api_key: ae89a4bad1274a2a9e9ae56c7ecf4cdb
:password: da38a39572b00bc89eed732ef4afa464
:theme_id: 3
:preview_url: https://bandup-seguro.tray.com.br/loja/loja.php?loja=365499&opencode_theme=588888af956dd
